
{{- if .Values.lapi.enabled }}
{{- if .Values.lapi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- if .Values.lapi.serviceAccount.annotations }}
    {{- toYaml .Values.lapi.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  name: {{ .Values.lapi.serviceAccount.name | default (printf "%s-lapi-sa" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Release.Name }}
    type: lapi
    version: v1
{{- end }}
{{- end }}
